# Generated by Django 4.1.7 on 2023-03-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='logitud',
            new_name='longitud',
        ),
    ]
