# Generated by Django 4.1.7 on 2023-03-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Procedimiento', '0002_rename_logitud_procedimiento_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimiento',
            old_name='cant_infraccionn',
            new_name='cant_infracciones',
        ),
    ]
