# Generated by Django 4.1.7 on 2023-03-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Operativos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_recursos', models.IntegerField()),
                ('fk_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operativos.operativo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fk_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(max_length=20)),
                ('fk_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.servicio')),
            ],
        ),
    ]
