# Generated by Django 4.1.7 on 2023-03-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporecurso',
            name='fk_servicio',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='fk_servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='fk_tipo_recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiporecurso'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fk_tipo_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiposervicio'),
        ),
    ]
