# Generated by Django 4.1.7 on 2023-03-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposervicio',
            old_name='descripcion',
            new_name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='fk_tipo_servicio',
        ),
        migrations.AddField(
            model_name='tiposervicio',
            name='fk_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='tiporecurso',
            name='tipo_recurso',
            field=models.TextField(),
        ),
    ]
