# Generated by Django 4.1.7 on 2023-03-07 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0002_rename_descripcion_tiposervicio_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposervicio',
            name='fk_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.servicio'),
        ),
    ]
