# Generated by Django 4.2.2 on 2023-07-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos/vigilancias/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
