# Generated by Django 4.1.7 on 2023-07-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/archivos/vigilancias/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
