# Generated by Django 4.1.7 on 2023-07-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Archivo', '0001_initial'),
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='fk_vigilancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.vigilancia'),
        ),
    ]
