# Generated by Django 4.1.7 on 2023-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to='vigilancias'),
        ),
    ]
