# Generated by Django 4.1.7 on 2023-07-19 20:51

import Archivo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0003_alter_documento_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='direccion',
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to=Archivo.models.directorio_dinamico),
        ),
    ]
