# Generated by Django 4.1.7 on 2023-07-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0004_remove_documento_direccion_documento_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='file',
            new_name='archivo',
        ),
    ]
