# Generated by Django 4.1.7 on 2023-07-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0005_rename_file_documento_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='file',
        ),
    ]
