# Generated by Django 4.1.7 on 2023-05-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cuil', models.BigIntegerField(primary_key=True, serialize=False)),
                ('dni', models.BigIntegerField()),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True)),
            ],
        ),
    ]
