# Generated by Django 4.1.7 on 2023-03-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='apellido',
            new_name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
    ]
