# Generated by Django 4.1.7 on 2023-05-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0002_alter_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
