# Generated by Django 4.1.7 on 2023-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Persona', '0003_alter_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
    ]
