# Generated by Django 4.1.7 on 2023-06-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prueba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_deleted',
        ),
    ]
