# Generated by Django 3.2.10 on 2023-03-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe_cargo', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('dependenciaOP', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=13)),
                ('cant_personas_afectadas', models.IntegerField()),
                ('cant_recursos', models.IntegerField()),
                ('procedimiento', models.BooleanField()),
                ('turno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OperativoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operativos.operativo')),
                ('fk_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.personal')),
            ],
        ),
    ]
