# Generated by Django 4.1.7 on 2023-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='personal',
            field=models.ManyToManyField(db_table='operativo_personal', related_name='personal', to='Operativos.operativopersonal'),
        ),
    ]
