# Generated by Django 4.1.7 on 2023-03-22 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operativos', '0003_rename_dependenciaop_operativo_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operativo',
            name='dependencia',
        ),
    ]
