# Generated by Django 4.1.7 on 2023-04-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0007_dependencia_operativos'),
        ('Operativos', '0004_remove_operativo_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='operativo',
            name='jurisdiccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia'),
        ),
        migrations.AddField(
            model_name='operativo',
            name='personal',
            field=models.ManyToManyField(db_table='operativo_personal', related_name='personal', to='Operativos.operativopersonal'),
        ),
    ]
