# Generated by Django 4.1.7 on 2023-03-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='operativos',
        ),
    ]
