# Generated by Django 4.1.7 on 2023-03-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='operativos',
            field=models.ManyToManyField(db_table='dependencia_operativos', related_name='operativos', to='Dependencia.dependenciaoperativos'),
        ),
    ]
