# Generated by Django 4.1.7 on 2023-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencia',
            old_name='jurisdicciones_op',
            new_name='jurisdiccion',
        ),
        migrations.AlterField(
            model_name='unidadregional',
            name='unidad_regional',
            field=models.CharField(default='', max_length=15),
        ),
    ]
