# Generated by Django 4.1.7 on 2023-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0003_rename_jurisdicciones_op_dependencia_jurisdiccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='jurisdiccion',
            field=models.CharField(max_length=100),
        ),
    ]
