# Generated by Django 4.1.7 on 2023-03-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0004_alter_dependencia_jurisdiccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='fk_inspectora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.inspectora'),
        ),
    ]
