# Generated by Django 4.1.7 on 2023-03-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0005_alter_dependencia_fk_inspectora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadregional',
            name='unidad_regional',
            field=models.CharField(default='', max_length=23),
        ),
    ]
