# Generated by Django 4.1.7 on 2023-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0006_alter_unidadregional_unidad_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='operativos',
            field=models.ManyToManyField(db_table='dependencia_operativos', null=True, related_name='operativos', to='Dependencia.dependenciaoperativos'),
        ),
    ]
