# Generated by Django 4.1.7 on 2023-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0007_dependencia_operativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='operativos',
            field=models.ManyToManyField(db_table='dependencia_operativos', related_name='operativos', to='Dependencia.dependenciaoperativos'),
        ),
    ]
