# Generated by Django 4.2.2 on 2023-06-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '0001_initial'),
        ('Dependencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True, null=True)),
                ('nombre_largo', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('fk_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia')),
                ('fk_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.jerarquia')),
                ('fk_jurisdiccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional')),
                ('fk_persona', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(null=True)),
                ('fk_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.cargo')),
                ('fk_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
            ],
        ),
    ]
