# Generated by Django 4.2 on 2023-05-23 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dependencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sumariante', models.BooleanField(default=False)),
                ('nombre_largo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEscalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_escalafon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_funcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jerarquia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('cuil', models.CharField(max_length=11, unique=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=8, null=True)),
                ('nombre_apellido', models.CharField(default='', max_length=80)),
                ('fecha_nacimiento', models.DateTimeField(default=models.DateField(verbose_name='01/01/1999'))),
                ('estado_civil', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('fk_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia')),
                ('fk_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.jerarquia')),
                ('fk_jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional')),
                ('fk_tipo_escalafon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipoescalafon')),
                ('fk_tipo_funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipofuncion')),
            ],
        ),
        migrations.AddField(
            model_name='jerarquia',
            name='fk_tipo_jerarquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipojerarquia'),
        ),
    ]
