# Generated by Django 4.1.7 on 2023-05-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0002_initial'),
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEscalafon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_escalafon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_funcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_jerarquia', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='personal',
            name='escalafon',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='estudios',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='fk_dependencia',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='funcion',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='jerarquia',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='oficio',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='prestacion_servicios',
        ),
        migrations.AddField(
            model_name='personal',
            name='fk_destino',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fk_jurisdiccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional'),
        ),
        migrations.CreateModel(
            name='Jerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sumariante', models.BooleanField(default=False)),
                ('nombre_largo', models.CharField(max_length=255)),
                ('fk_tipo_jerarquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipojerarquia')),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='fk_jerarquia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.jerarquia'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fk_tipo_escalafon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.tipoescalafon'),
        ),
        migrations.AddField(
            model_name='personal',
            name='fk_tipo_funcion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.tipofuncion'),
        ),
    ]
