# Generated by Django 4.1.7 on 2023-07-18 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='fk_sub_categoria',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fk_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.subcategoria'),
        ),
    ]
