# Generated by Django 4.1.7 on 2023-06-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0002_cargo_jerarquia_activo_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='jerarquia',
            name='activo',
            field=models.BooleanField(),
        ),
    ]
