# Generated by Django 4.1.7 on 2023-05-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0002_initial'),
        ('Personal', '0002_tipoescalafon_tipofuncion_tipojerarquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fk_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fk_jerarquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.jerarquia'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fk_jurisdiccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fk_tipo_escalafon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipoescalafon'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='fk_tipo_funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.tipofuncion'),
        ),
    ]
