# Generated by Django 4.1.7 on 2023-05-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_alter_personal_fk_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='cuil',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
