# Generated by Django 4.1.7 on 2023-06-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0003_alter_cargo_activo_alter_jerarquia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jerarquia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
