# Generated by Django 4.1.7 on 2023-06-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0004_alter_cargo_activo_alter_jerarquia_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='jerarquia',
            name='activo',
        ),
    ]
