# Generated by Django 4.1.7 on 2023-06-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0005_remove_cargo_activo_remove_jerarquia_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='jerarquia',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
