# Generated by Django 4.1.7 on 2023-03-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rol'),
        ),
    ]
