# Generated by Django 4.1.7 on 2023-03-31 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0006_alter_unidadregional_unidad_regional'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='jurisdiccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='regional',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Jurisdicion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Unidad aRegional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional'),
        ),
    ]
