# Generated by Django 4.1.7 on 2023-03-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuario_jurisdiccion_remove_usuario_regional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Jurisdicion',
            new_name='jurisdicion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Unidad aRegional',
            new_name='unidada_regional',
        ),
    ]
