# Generated by Django 4.1.7 on 2023-03-31 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_jurisdicion_usuario_jurisdicion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='jurisdicion',
            new_name='jurisdiccion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='unidada_regional',
            new_name='unidad_regional',
        ),
    ]
