# Generated by Django 4.1.7 on 2023-02-23 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_permiso', models.CharField(default='operador', max_length=50, verbose_name='nivel permiso')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'permissions': (('administrador', 'Administrador'), ('operador', 'Operador'), ('general', 'General')),
            },
        ),
    ]
