# Generated by Django 4.1.7 on 2023-04-03 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0006_alter_unidadregional_unidad_regional'),
        ('users', '0006_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='jurisdiccion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='unidad_regional',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional'),
        ),
    ]
