# Generated by Django 4.1.7 on 2023-03-09 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('destino', models.CharField(max_length=50)),
                ('disposicion', models.CharField(max_length=50)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=13)),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=13)),
                ('fk_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiposervicio')),
            ],
        ),
        migrations.CreateModel(
            name='DiasVigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia_completo', models.BooleanField(default=False)),
                ('fk_vigilancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.vigilancia')),
            ],
        ),
    ]
