# Generated by Django 4.1.7 on 2023-04-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diasvigilancia',
            name='fk_personal',
        ),
        migrations.CreateModel(
            name='PersonalDiaVigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_fin', models.TimeField(null=True)),
                ('fk_diaVigilancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.diasvigilancia')),
                ('fk_personal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.personal')),
            ],
        ),
    ]
