# Generated by Django 4.1.7 on 2023-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilancia',
            name='comisaria',
            field=models.CharField(default='', max_length=50),
        ),
    ]
