# Generated by Django 4.1.7 on 2023-05-02 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosvigilancia',
            name='turno',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
