# Generated by Django 4.1.7 on 2023-03-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0004_alter_dependencia_jurisdiccion'),
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilancia',
            name='jurisdiccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencia.dependencia'),
        ),
    ]
