# Generated by Django 4.1.7 on 2023-04-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dependencia', '0002_initial'),
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigilancia',
            name='regional',
        ),
        migrations.AddField(
            model_name='vigilancia',
            name='fk_unidad_regional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional'),
        ),
    ]
