# Generated by Django 4.1.7 on 2023-06-15 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0006_cargo_activo_jerarquia_activo'),
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vigilancia',
            name='fk_funcionario',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.funcionario'),
        ),
        migrations.CreateModel(
            name='ArchivoVigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('fk_vigilancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.vigilancia')),
            ],
        ),
        migrations.AddField(
            model_name='vigilancia',
            name='fk_ente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.ente'),
        ),
    ]
