# Generated by Django 4.1.7 on 2023-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalvigilancia',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
