# Generated by Django 4.1.7 on 2023-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0002_personalvigilancia_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalvigilancia',
            name='duracion',
            field=models.IntegerField(),
        ),
    ]
