# Generated by Django 4.1.7 on 2023-04-12 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
        ('Vigilancia', '0002_remove_diasvigilancia_fk_personal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoVigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='diasvigilancia',
            old_name='dia',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='diasvigilancia',
            name='turno',
        ),
        migrations.DeleteModel(
            name='PersonalDiaVigilancia',
        ),
        migrations.AddField(
            model_name='turnovigilancia',
            name='fk_diaVigilancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.diasvigilancia'),
        ),
        migrations.AddField(
            model_name='turnovigilancia',
            name='fk_personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Personal.personal'),
        ),
    ]
