# Generated by Django 4.1.7 on 2023-03-30 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0002_remove_tiporecurso_fk_servicio_and_more'),
        ('Vigilancia', '0002_alter_vigilancia_jurisdiccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoVigilancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=22)),
            ],
        ),
        migrations.RenameField(
            model_name='vigilancia',
            old_name='jurisdiccion',
            new_name='fk_jurisdiccion',
        ),
        migrations.RemoveField(
            model_name='vigilancia',
            name='fk_tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='vigilancia',
            name='motivo',
        ),
        migrations.AddField(
            model_name='vigilancia',
            name='fk_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicio.servicio'),
        ),
    ]
