# Generated by Django 4.1.7 on 2023-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0002_alter_turnosvigilancia_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalvigilancia',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
