# Generated by Django 4.1.7 on 2023-03-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0002_vigilancia_comisaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigilancia',
            name='disposicion',
        ),
    ]
