# Generated by Django 4.1.7 on 2023-03-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0003_motivovigilancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilancia',
            name='fk_motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.motivovigilancia'),
        ),
    ]
