# Generated by Django 4.1.7 on 2023-05-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0004_alter_personalvigilancia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnosvigilancia',
            name='fecha',
        ),
    ]
