# Generated by Django 4.1.7 on 2023-03-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
        ('Vigilancia', '0004_vigilancia_fk_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diasvigilancia',
            name='fk_personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.personal'),
        ),
    ]
