# Generated by Django 4.1.7 on 2023-06-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0004_alter_vigilancia_fk_ente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivoVigilancia',
            new_name='Archivo',
        ),
    ]
