# Generated by Django 4.1.7 on 2023-04-25 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0001_initial'),
        ('Dependencia', '0002_initial'),
        ('Vigilancia', '0004_alter_vigilancia_fk_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vigilancia',
            name='fk_motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.motivo'),
        ),
        migrations.AlterField(
            model_name='vigilancia',
            name='fk_tipo_recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiporecurso'),
        ),
        migrations.AlterField(
            model_name='vigilancia',
            name='fk_tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='vigilancia',
            name='fk_unidad_regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dependencia.unidadregional'),
        ),
    ]
