# Generated by Django 4.1.7 on 2023-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0005_remove_turnosvigilancia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilancia',
            name='turno_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
