# Generated by Django 4.1.7 on 2023-04-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0005_alter_diasvigilancia_fk_personal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotivoVigilancia',
            new_name='Motivo',
        ),
    ]
