# Generated by Django 4.1.7 on 2023-04-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicio', '0002_remove_tiporecurso_fk_servicio_and_more'),
        ('Vigilancia', '0006_rename_motivovigilancia_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigilancia',
            name='fk_servicio',
        ),
        migrations.AddField(
            model_name='vigilancia',
            name='fk_tipo_recurso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiporecurso'),
        ),
        migrations.AddField(
            model_name='vigilancia',
            name='fk_tipo_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Servicio.tiposervicio'),
        ),
        migrations.AlterField(
            model_name='vigilancia',
            name='cant_dias',
            field=models.IntegerField(default=0),
        ),
    ]
