# Generated by Django 4.1.7 on 2023-05-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0006_vigilancia_turno_asignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vigilancia',
            name='turnos_vigilancias',
        ),
        migrations.AlterField(
            model_name='turnosvigilancia',
            name='fk_vigilancia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.vigilancia'),
        ),
    ]
