# Generated by Django 4.1.7 on 2023-04-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0007_remove_vigilancia_fk_servicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diasvigilancia',
            old_name='fk_personal',
            new_name='fk_personaldia',
        ),
    ]
