# Generated by Django 4.1.7 on 2023-05-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0007_remove_vigilancia_turnos_vigilancias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnosvigilancia',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
