# Generated by Django 4.1.7 on 2023-04-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0008_rename_fk_personal_diasvigilancia_fk_personaldia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diasvigilancia',
            old_name='fk_personaldia',
            new_name='fk_personal',
        ),
    ]
