# Generated by Django 4.1.7 on 2023-05-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
        ('Vigilancia', '0008_turnosvigilancia_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalvigilancia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='personalvigilancia',
            name='fk_personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Personal.personal'),
        ),
        migrations.AlterField(
            model_name='turnosvigilancia',
            name='fk_vigilancia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vigilancia.vigilancia'),
        ),
    ]
