# Generated by Django 4.1.7 on 2023-05-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0009_alter_personalvigilancia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalvigilancia',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
