# Generated by Django 4.1.7 on 2023-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0009_rename_fk_personaldia_diasvigilancia_fk_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vigilancia',
            name='dias_vigilancias',
            field=models.ManyToManyField(db_table='vigilancia_diasvigilancia', related_name='dias_vigilancias', to='Vigilancia.diasvigilancia'),
        ),
    ]
