# Generated by Django 4.1.7 on 2023-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vigilancia', '0010_personalvigilancia_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnosvigilancia',
            name='duracion',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
